# Automatically approve certain Pu
# which will be auto-approved.
name: Autoapprove

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    if: |
      github.event.pull_request.user.login == 'weblate' ||
      contains(github.event.pull_request.labels.*.name, 'translations')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v4.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
