name: Deploy to hedy.org
on:
  # This gets run by hand
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Restrict who can run this workflow
      - if: github.actor != 'Felienne' && github.actor != 'jpelay'
        run: |
          echo "You must be Felienne to run this workflow :D" >&2
          exit 1
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hedy-beta
          heroku_email: felienne@gmail.com
