# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# If you change this name, don't forget to change deploy-to-alpha.yml
name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install Nodejs dependencies
      run: |
        npm ci
    - name: Generate grammar files
      run: |
        python ./content/yaml_to_lark_utils.py
    - name: Compiling Babel translations
      run: |
        pybabel compile -f -d translations
    - name: Check for changed files in grammar related directories
      shell: pwsh
      id: check_file_changed
      run: |
        $diff = git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
        $SourceDiff = $diff | Where-Object { $_ -match '^content/' -or $_ -match '^grammars/' -or $_ -match '^highlighting/' -or $_ -match '^tests/' -or $_ -match '^app.py' -or $_ -match '^hedy.py'}
        $HasDiff = $SourceDiff.Length -gt 0
        Write-Host "::set-output name=docs_changed::$HasDiff"
    - name: Run weblate tests
      shell: pwsh
      id: weblate_tests
      if: ${{ github.event.pull_request.user.login == 'weblate' }}
      run: |
        Write-Host "::set-output name=run::True"
        build-tools/github/validate --weblate
    - name: Run all tests
      shell: pwsh
      if: ${{(steps.check_file_changed.outputs.docs_changed == 'True' || github.event.label.name == 'force_tests') && steps.check_file_changed.weblate_tests.run != 'True'}}
      run: |
        build-tools/github/validate --all
    - name: Run non-code related tests
      shell: pwsh
      if: ${{steps.check_file_changed.outputs.docs_changed != 'True' && steps.weblate_tests.run != 'True'}}
      run: |
        build-tools/github/validate
